
spring.datasource.url=jdbc:postgresql://localhost:5432/StudentManage
spring.datasource.username=postgres
spring.datasource.password=123kimlong

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
